language: java
sudo: false

os:
  - linux
  - osx

jdk:
  - openjdk8
  - openjdk11

script: ./mvnw install && ./mvnw test

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh
